//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.14

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "character")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: String,
    pub name: String,
    pub tag: String,
    pub ideology: Option<String>,
    pub positions: Option<String>,
    #[sea_orm(column_name = "leaderTraits")]
    pub leader_traits: Option<String>,
    #[sea_orm(column_name = "leaderIdeologies")]
    pub leader_ideologies: Option<String>,
    #[sea_orm(column_name = "commanderTraits")]
    pub commander_traits: Option<String>,
    #[sea_orm(column_name = "advisorRoles")]
    pub advisor_roles: Option<String>,
    pub roles: Option<String>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
