//! `SeaORM` Entity, @generated by sea-orm-codegen 1.0.0

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "focus")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false, column_type = "Text")]
    pub id: String,
    #[sea_orm(column_type = "Text")]
    pub name: String,
    #[sea_orm(column_type = "Text")]
    pub tag: String,
    pub position_x: Option<i32>,
    pub position_y: Option<i32>,
    #[sea_orm(column_type = "Text", nullable)]
    pub relatives: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub prerequisites: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub exclusives: Option<String>,
    pub cost: Option<i32>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
